spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storedatabase
    username: root
    password: La@456shitha
    driver-class-name: com.mysql.cj.jdbc.Driver



#  jpa:
#    show-sql: true


    hibernate:
      ddl-auto: update